//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirObservationSystem.HHU.Core.Resx {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AirObservationSystem.HHU.Core.Resx.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string BtnLogin {
            get {
                return ResourceManager.GetString("BtnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string BtnLogout {
            get {
                return ResourceManager.GetString("BtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string BtnOk {
            get {
                return ResourceManager.GetString("BtnOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string BtnReports {
            get {
                return ResourceManager.GetString("BtnReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string BtnSend {
            get {
                return ResourceManager.GetString("BtnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        internal static string BtnUnlock {
            get {
                return ResourceManager.GetString("BtnUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to change the communication Type?.
        /// </summary>
        internal static string ChangeConnectionMessage {
            get {
                return ResourceManager.GetString("ChangeConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Communication Type.
        /// </summary>
        internal static string ChangeConnectionTitle {
            get {
                return ResourceManager.GetString("ChangeConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find the Device.
        /// </summary>
        internal static string ConnectionFailedText {
            get {
                return ResourceManager.GetString("ConnectionFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string ConnectionFailedTitle {
            get {
                return ResourceManager.GetString("ConnectionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit ?.
        /// </summary>
        internal static string ExitMessage {
            get {
                return ResourceManager.GetString("ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Confirmation.
        /// </summary>
        internal static string ExitTitle {
            get {
                return ResourceManager.GetString("ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AECL - King Khalid International Airport, Industrial Estate, Riyadh, Saudi Arabia.
        /// </summary>
        internal static string LblAboutAddress {
            get {
                return ResourceManager.GetString("LblAboutAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand Held Unit - Air Ovservation System.
        /// </summary>
        internal static string LblAboutAppName {
            get {
                return ResourceManager.GetString("LblAboutAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is property of AECL, if found please return to E&amp;D department. AASC Building.
        /// </summary>
        internal static string LblAboutAuth {
            get {
                return ResourceManager.GetString("LblAboutAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string LblAboutPageName {
            get {
                return ResourceManager.GetString("LblAboutPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify Airborne Craft.
        /// </summary>
        internal static string LblAirborneCraftPageName {
            get {
                return ResourceManager.GetString("LblAirborneCraftPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string LblAltitudePageName {
            get {
                return ResourceManager.GetString("LblAltitudePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIR OBSERVATION SYSTEM.
        /// </summary>
        internal static string LblAplicationName {
            get {
                return ResourceManager.GetString("LblAplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audible.
        /// </summary>
        internal static string LblAudible {
            get {
                return ResourceManager.GetString("LblAudible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        internal static string LblBluetooth {
            get {
                return ResourceManager.GetString("LblBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civilian.
        /// </summary>
        internal static string LblCivilian {
            get {
                return ResourceManager.GetString("LblCivilian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Communication Interface.
        /// </summary>
        internal static string LblCommunicationSelectionPageName {
            get {
                return ResourceManager.GetString("LblCommunicationSelectionPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Message.
        /// </summary>
        internal static string LblComposeMsgPageName {
            get {
                return ResourceManager.GetString("LblComposeMsgPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drone.
        /// </summary>
        internal static string LblDrone {
            get {
                return ResourceManager.GetString("LblDrone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East.
        /// </summary>
        internal static string LblEast {
            get {
                return ResourceManager.GetString("LblEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fighter.
        /// </summary>
        internal static string LblFighter {
            get {
                return ResourceManager.GetString("LblFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        internal static string LblFilter {
            get {
                return ResourceManager.GetString("LblFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        internal static string LblHeadingPageName {
            get {
                return ResourceManager.GetString("LblHeadingPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter.
        /// </summary>
        internal static string LblHelicopter {
            get {
                return ResourceManager.GetString("LblHelicopter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string LblHigh {
            get {
                return ResourceManager.GetString("LblHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string LblLow {
            get {
                return ResourceManager.GetString("LblLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        internal static string LblMid {
            get {
                return ResourceManager.GetString("LblMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transport.
        /// </summary>
        internal static string LblMilitary {
            get {
                return ResourceManager.GetString("LblMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to North.
        /// </summary>
        internal static string LblNorth {
            get {
                return ResourceManager.GetString("LblNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Base.
        /// </summary>
        internal static string LblObservationBase {
            get {
                return ResourceManager.GetString("LblObservationBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify Observation Number.
        /// </summary>
        internal static string LblObservationNumberPageName {
            get {
                return ResourceManager.GetString("LblObservationNumberPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define Observation Type.
        /// </summary>
        internal static string LblObservationTypePageName {
            get {
                return ResourceManager.GetString("LblObservationTypePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string LblOne {
            get {
                return ResourceManager.GetString("LblOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Base.
        /// </summary>
        internal static string LblOperationBase {
            get {
                return ResourceManager.GetString("LblOperationBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string LblReportsPageName {
            get {
                return ResourceManager.GetString("LblReportsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        internal static string LblSerial {
            get {
                return ResourceManager.GetString("LblSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South.
        /// </summary>
        internal static string LblSouth {
            get {
                return ResourceManager.GetString("LblSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string LblText {
            get {
                return ResourceManager.GetString("LblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Summary.
        /// </summary>
        internal static string lblTextMessageSummaryPageName {
            get {
                return ResourceManager.GetString("lblTextMessageSummaryPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Message Type.
        /// </summary>
        internal static string lblTextMessageTypePageName {
            get {
                return ResourceManager.GetString("lblTextMessageTypePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string LblThreeOrMore {
            get {
                return ResourceManager.GetString("LblThreeOrMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string LblTwo {
            get {
                return ResourceManager.GetString("LblTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidentified.
        /// </summary>
        internal static string LblUnidentified {
            get {
                return ResourceManager.GetString("LblUnidentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual.
        /// </summary>
        internal static string LblVisual {
            get {
                return ResourceManager.GetString("LblVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to West.
        /// </summary>
        internal static string LblWest {
            get {
                return ResourceManager.GetString("LblWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HHU has been locked
        ///and the base has been notified.
        /// </summary>
        internal static string LockMsg {
            get {
                return ResourceManager.GetString("LockMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed, Please try again..
        /// </summary>
        internal static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to logout?.
        /// </summary>
        internal static string LogoutMessage {
            get {
                return ResourceManager.GetString("LogoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopPagesAsync.
        /// </summary>
        internal static string LogoutTitle {
            get {
                return ResourceManager.GetString("LogoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Center.
        /// </summary>
        internal static string MessageDirectionObservation {
            get {
                return ResourceManager.GetString("MessageDirectionObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Operation.
        /// </summary>
        internal static string MessageDirectionOperation {
            get {
                return ResourceManager.GetString("MessageDirectionOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        internal static string MessageTypeAlerts {
            get {
                return ResourceManager.GetString("MessageTypeAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string MessageTypeNotifications {
            get {
                return ResourceManager.GetString("MessageTypeNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warrnings.
        /// </summary>
        internal static string MessageTypeWarrnings {
            get {
                return ResourceManager.GetString("MessageTypeWarrnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string TxtPassword {
            get {
                return ResourceManager.GetString("TxtPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string TxtUsername {
            get {
                return ResourceManager.GetString("TxtUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
